### ISSUE TITLE
Assign a zdouble to a double

### ISSUE THREAD

**Issue by Loutjie** [coin-or/CppAD#11]
The following operator can be added to zdouble to allow it to be assigned to a double:

// Return double version of zdouble
	operator double() const 
	{ 
		return dbl_; 
	}

**Comment by bradbell** [comment]
It seems to me that the solution for this issue would also solve 
  https://github.com/coin-or/CppAD/issues/10
without any additional code. I do not currently have a Visual studio system set up to try this (and am busy with other things right now), so perhaps Loutjie can check this out.

**Comment by bradbell** [comment]
Would you please provide a simple example that results in the warnings you intend to fix here and (so I can add it to the CppAD tests to make sure that the fix works).

**Comment by Loutjie** [comment]
Hi Brad

 

This problem resulted in the compilation error for me. Simple code to test this:

 

CppAD::zdouble zValue = 10.0;

double dValue = zValue;

 

Kind regards

Loutjie

**Comment by bradbell** [comment]
I think that this issue is closed for the following two reasons:
1. Most all the visual studio warnings have been fixed; see issue #10 
2. The type zdouble is no longer needed for multiple level AD and has been deprecated; see the heading 09-27 on
This is mentioned under the heading 09-24 on
   http://www.coin-or.org/CppAD/Doc/whats_new_15.htm#09-24
