### ISSUE TITLE
Converting AD<double> to double

### ISSUE THREAD

**Issue by vimalrajayyappan** [coin-or/CppAD#66]
Thanks a lot for your valuable package. Please help me in converting from AD<> datatype to its base type. Normal Typecasting is not working. Thanks a lot :)

**Comment by vimalrajayyappan** [comment]
I found the way. There is a function in **CppAd::Value(AD<>)** will give the value.


Let it help others too. Thanks

**Comment by vimalrajayyappan** [comment]
While I was getting my code Compiled. Its showing error while Runtime. Kindly help me with this. The error is

cppad-20160000.1 error from a known source:
Value: argument is a variable (not a parameter)
Error detected by false result for
    Parameter(x)

**Comment by bradbell** [comment]
You can only extract the value for a parameter (a parameter does not depend on the independent variables). This is because the value of an AD<Base> object had type Base and does not track dependency on AD<Base> independent variables. If you really want the value with out the dependency, use Var2Par;
https://coin-or.github.io/CppAD/doc/var2par.htm

**Comment by vimalrajayyappan** [comment]
Dear BradBel. Exactly solved the issue..nice

 But I got stuck with one more issue. When I'm converting the variable using Var2Par in cost functions, the optimiser is not recognising the cost.. Its not even considering the cost even though he values are high. Can you help? 

I  know this explanation  makes no meaning. But I figured it out in that way.

**Comment by bradbell** [comment]
Why are you using the Value function ?

**Comment by vimalrajayyappan** [comment]
Actually there are certain implementations where I'm using "double" datatype. Which is causing a typecasting issue. He c I'm using CppAD::Value to get it to its base type and feed them.

**Comment by bradbell** [comment]
As I mentioned, but perhaps was not clear about, all the derivatives of the Value(y) are zero, even it the derivatives of y are not zero. It you need to track the dependency (derivatives) you need to use an AD type.

**Comment by vimalrajayyappan** [comment]
Thanks Brad Bell. You are great and thanks for ur time in explaining. Also I will dig deep into the doc as well. Cheers😊

**Comment by vimalrajayyappan** [comment]
One good example I can give you.

The points getting optimised are in global frame. I'm having a common.hpp file where there is a transformation function using double. I need to use that function to transform points in local frame. Hence typecasting..

But from your answer I get to know we must use Ad<Double> to track. Is tat ryt?

**Comment by bradbell** [comment]
If the source for the transformation is not to large, convert it to a function where double is replaced by a template parameter so that you can use the source code with both double and AD<double>.

Also, it sounds like (but I am not sure) you are interpolating values, so you may want to look at
https://coin-or.github.io/CppAD/doc/interp_onetape.cpp.htm
https://coin-or.github.io/CppAD/doc/interp_retape.cpp.htm

**Comment by vimalrajayyappan** [comment]
Dear BradBel. Thanks a lot for your kind help. I will dig into the links u have shared. 😊
